# Generated by Django 5.2.6 on 2025-10-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
