# Generated by Django 5.2.6 on 2025-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_id_review_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
