# Generated by Django 5.2.6 on 2025-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='book.genre'),
        ),
    ]
