# Generated by Django 5.2.6 on 2025-10-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_genre_created_on_alter_genre_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerlist',
            name='genres',
        ),
    ]
